name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    if: ${{ env.RUN_DEPLOY != 'false' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      # Step 3: Build with Maven
      - name: Build with Maven
        id: maven_build
        run: mvn clean package

      - name: Log in to Docker Hub
        if: success()
        env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
         echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || exit 1

      # Step 5: Build the Docker image only if Maven build succeeds
      - name: Build Docker image
        if: success()
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/books_api:latest .

      # Step 6: Push the Docker image to Docker Hub only if Docker build succeeds
      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/books_api:latest
